import { Component, OnDestroy } from '@angular/core'; import { Subscription, interval, switchMap } from 'rxjs'; import { VideoJob, JobStatus } from './models'; import { VideoJobService } from './video-job.service';
@Component({ selector: 'app-root', templateUrl: './app.component.html', styleUrl: './app.component.css' })
export class AppComponent implements OnDestroy {
  product?: File; reference?: File; productPreview?: string; referencePreview?: string; description = ''; style = ''; job?: VideoJob; submitting = false; error = ''; private polling?: Subscription;
  readonly stages: JobStatus[] = ['Pending', 'Analyzing', 'PromptGenerated', 'Rendering', 'Completed'];
  constructor(private readonly jobs: VideoJobService) {}
  choose(kind: 'product' | 'reference', event: Event): void { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 10 * 1024 * 1024) { this.error = 'Use JPG, PNG or WEBP images under 10 MB.'; return; } this.error = ''; const preview = URL.createObjectURL(file); if (kind === 'product') { this.product = file; this.productPreview = preview; } else { this.reference = file; this.referencePreview = preview; } }
  generate(): void { if (!this.product || !this.reference || !this.description.trim()) { this.error = 'Add both images and a product description before generating.'; return; } this.polling?.unsubscribe(); this.submitting = true; this.error = ''; const form = new FormData(); form.append('productImage', this.product); form.append('referenceImage', this.reference); form.append('userDescription', this.description); form.append('style', this.style); this.jobs.create(form).subscribe({ next: job => { this.job = job; this.submitting = false; this.polling = interval(2500).pipe(switchMap(() => this.jobs.get(job.id))).subscribe({ next: current => { this.job = current; if (current.status === 'Completed' || current.status === 'Failed') this.polling?.unsubscribe(); }, error: () => { this.error = 'Could not refresh this job. Please try again.'; this.polling?.unsubscribe(); } }); }, error: response => { this.submitting = false; this.error = response.error || 'Could not create the video job.'; } }); }
  isActive(stage: JobStatus): boolean { return !!this.job && this.stages.indexOf(stage) <= this.stages.indexOf(this.job.status) && this.job.status !== 'Failed'; }
  ngOnDestroy(): void { this.polling?.unsubscribe(); }
}
