using Microsoft.EntityFrameworkCore;
using VideoGen.Api.Services;
using VideoGen.Application.Abstractions;
using VideoGen.Infrastructure.Options;
using VideoGen.Infrastructure.Persistence;
using VideoGen.Infrastructure.Services;
var builder = WebApplication.CreateBuilder(args);
builder.Services.Configure<OpenAiOptions>(builder.Configuration.GetSection("OpenAI"));
builder.Services.Configure<ComfyUiOptions>(builder.Configuration.GetSection("ComfyUI"));
builder.Services.Configure<StorageOptions>(builder.Configuration.GetSection("Storage"));
builder.Services.AddDbContext<VideoGenDbContext>(o => o.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));
builder.Services.AddScoped<IVideoJobRepository, EfVideoJobRepository>();
builder.Services.AddHttpClient<IAiPromptService, OpenAiPromptService>(c => c.BaseAddress = new Uri("https://api.openai.com/"));
builder.Services.AddHttpClient<IComfyUiClient, ComfyUiClient>((sp, c) => c.BaseAddress = new Uri(sp.GetRequiredService<Microsoft.Extensions.Options.IOptions<ComfyUiOptions>>().Value.BaseUrl.TrimEnd('/') + "/"));
builder.Services.AddHostedService<VideoJobWorker>(); builder.Services.AddControllers(); builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen();
builder.Services.AddCors(o => o.AddPolicy("frontend", p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
var app = builder.Build();
app.UseSwagger(); app.UseSwaggerUI(); app.UseCors("frontend"); app.MapControllers();
using (var scope = app.Services.CreateScope()) await scope.ServiceProvider.GetRequiredService<VideoGenDbContext>().Database.MigrateAsync();
app.Run();
